# This is a basic workflow to help you get started with Actions

name: WindowsPS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # # Service containers to run with `runner-job`
    # services:
    #   # Label used to access the service container
    #   redis:
    #     # Docker Hub image
    #     image: mcr.microsoft.com/mssql/server:2019-latest
    #     #
    #     ports:
    #       # Opens tcp port 6379 on the host and service container
    #       - 1433:1433
    #     env:
    #       ACCEPT_EULA: Y
    #       SA_PASSWORD: P@$sw0rdling

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: powershell -c 'Get-Service | Where-Object {$_.name -like ''*MSSQLSERVER*'' -and $_.status -ne ''Running''} | start-service'
    
    # Install SQL Express
    # - name: Install SQL Express
    #   run: powershell -F ./Build/Install-SqlExpress.ps1

    # install dacpac
    # - name: Install dacpac
    #   run: >
    #     & "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\Extensions\\Microsoft\\SQLDB\\DAC\\150\\sqlpackage.exe" 
    #     /Action:Publish 
    #     /SourceFile:"all1.dacpac" 
    #     /TargetServerName:"${{ Secrets.SQLHOST }}" 
    #     /TargetDatabaseName:"all1" 
    #     /TargetUser:"${{ Secrets.SQL_USER }}" 
    #     /TargetPassword:"${{ Secrets.SQL_PASSWD }}" 
    #     /p:BlockOnPossibleDataLoss=False
     
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env: 
        SQLHOST: ${{ Secrets.SQLHOST }}
        SQL_USER: ${{ Secrets.SQL_USER }}
        SQL_PASSWD: ${{ Secrets.SQL_PASSWD }}
      run: |
        cd $ENV:GITHUB_WORKSPACE
        powershell -F ./Test.ps1

        
